#ifndef _CPPERRORS_H_
#define _CPPERRORS_H_

//#define FUNCTION_NOT_DEFINED_ERROR
//#define SCOPE_ERROR
//#define CANNOT_CONVERT_ERROR
//#define MISSING_PARENTHESIS_ERROR
//#define UNRESOLVED_EXTERNAL_ERROR

#endif /* _CPPERRORS_H_ */
